import React, {useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import {Activity, AlertTriangle, BarChart3, Beaker, Check, CheckCircle2, ChevronRight, ClipboardCheck, Database, Download, Droplets, FileCheck2, FileSpreadsheet, Gauge, Home, Import, Menu, Plus, Save, Settings2, ShieldAlert, SlidersHorizontal, Upload, X, XCircle} from 'lucide-react';
import './styles.css';

type Row={condition:'AS_FOUND'|'POST_K';timestamp:string;use:boolean;duration:number;p:number;t:number;dp:number;gvf:number;wlr:number;oil:number;gas:number;water:number;oilCorr?:number;gasCorr?:number;waterCorr?:number};
type SeparatorRow={condition:string,timestamp:string,use_flag:number,duration_h:number|null,quality:string,pressure_barg:number|null,temperature_c:number|null,oil_gv_line_m3:number|null,oil_rho_coriolis_kgm3:number|null,oil_mass_direct_t:number|null,gas_mass_t:number|null,water_mass_t:number|null,gas_std_ksm3:number|null,water_vol_m3:number|null,source_ref:string};
type LabResult={sample_id:string,use_flag:number,sampled_at:string,sample_type:string,bsw_pct:number|null,rho_oil_std_kgm3:number|null,rho_gas_std_kgsm3:number|null,rho_water_std_kgm3:number|null,fe:number|null,rs:number|null,method:string,report_id:string,status:string};
type MpfmExtractRow={timestamp:string,use:boolean,duration:number|null,quality:string,p:number|null,t:number|null,dp:number|null,gvf:number|null,wlr:number|null,oil:number|null,gas:number|null,water:number|null,oilCorr:number|null,gasCorr:number|null,waterCorr:number|null};
type SeparatorExtractRow={timestamp:string,use:boolean,durationH:number|null,quality:string,pressureBarg:number|null,temperatureC:number|null,oilGvLineM3:number|null,oilRhoCoriolisKgm3:number|null,oilMassDirectT:number|null,gasMassT:number|null,waterMassT:number|null,gasStdKsm3:number|null,waterVolM3:number|null,sourceRef:string};
type Campaign={id:string,revision:string,nature:string,asset:string,well:string,tag:string,serial:string,type:string,reference:string,start:string,end:string,postStart:string,postEnd:string,pb:number,hcLimit:number,totalLimit:number,pvtLimit:number,kMin:number,kMax:number,minRecords:number,pvtMonths:number,timezone:string,responsible:string,approver:string,envelope:{p:[number|null,number|null],t:[number|null,number|null],dp:[number|null,number|null],gvf:[number|null,number|null],wlr:[number|null,number|null]},pvt:{asOil:number,asGas:number,asWater:number,postOil:number,postGas:number,postWater:number,file:string,hash:string,software:string,version:string,approver:string},uncertainty:{asMpfm:number,asRef:number,postMpfm:number,postRef:number},k:{oilApproved:number,gasApproved:number,waterApproved:number,oilApplied:number,gasApplied:number,waterApplied:number,date:string,responsible:string,evidence:string},integrity:{raw:boolean,dp:boolean,units:boolean,timezone:boolean,gaps:boolean,exclusions:boolean},evidence:boolean,approvals:boolean,rows:Row[],raw?:{separatorRows:SeparatorRow[],labResults:LabResult[]}};

const sampleRows:Row[] = Array.from({length:48},(_,i)=>{const post=i>=24; const base=post?i-24:i; return {condition:post?'POST_K':'AS_FOUND',timestamp:new Date(Date.UTC(2026,5,29+(post?4:0),12+base)).toISOString(),use:true,duration:1,p:116+Math.sin(base/3)*2,t:68+Math.cos(base/5)*1.8,dp:43+Math.sin(base/2)*4,gvf:65+Math.sin(base/4)*5,wlr:0,oil:post?7900/24:8090.398/24,gas:post?1830/24:1854.678/24,water:0,oilCorr:post?8290/24:undefined,gasCorr:post?1890.074/24:undefined,waterCorr:0}});
const initial:Campaign={id:'RVD-MPFM-COM-05-26',revision:'Rev. 0',nature:'COMISSIONAMENTO',asset:'FPSO Bacalhau',well:'Riser P4 / PW-104DA',tag:'13FT0317',serial:'13-100060',type:'TOPSIDE — RISER P4',reference:'Separador de Teste 20VA121',start:'2026-06-29T12:00',end:'2026-06-30T12:00',postStart:'2026-07-03T00:00',postEnd:'2026-07-04T00:00',pb:480,hcLimit:.10,totalLimit:.07,pvtLimit:.01,kMin:.8,kMax:1.2,minRecords:24,pvtMonths:6,timezone:'',responsible:'',approver:'',envelope:{p:[null,null],t:[null,null],dp:[null,null],gvf:[null,null],wlr:[null,null]},pvt:{asOil:8300.167244,asGas:1890.24,asWater:0,postOil:8354.806,postGas:1890.074,postWater:0,file:'',hash:'',software:'PVTPack / Calsep',version:'',approver:''},uncertainty:{asMpfm:5,asRef:.895015,postMpfm:5,postRef:.894958},k:{oilApproved:1.025928,gasApproved:1.019174,waterApproved:1,oilApplied:1.025928,gasApplied:1.019174,waterApplied:1,date:'2026-06-30T12:00',responsible:'Gabriel Chargue',evidence:'FCS/HMI'},integrity:{raw:true,dp:true,units:true,timezone:false,gaps:true,exclusions:true},evidence:false,approvals:false,rows:sampleRows};

const sum=(rows:Row[],key:keyof Row)=>rows.reduce((a,r)=>a+(r.use?(Number(r[key])||0):0),0);
export function calculate(c:Campaign){
 const as=c.rows.filter(r=>r.condition==='AS_FOUND'), post=c.rows.filter(r=>r.condition==='POST_K');
 const asOil=sum(as,'oil'),asGas=sum(as,'gas'),asWater=sum(as,'water'),asHC=asOil+asGas,asTotal=asHC+asWater,refHC=c.pvt.asOil+c.pvt.asGas,refTotal=refHC+c.pvt.asWater;
 const postOil=sum(post,'oilCorr'),postGas=sum(post,'gasCorr'),postWater=sum(post,'waterCorr'),postHC=postOil+postGas,postTotal=postHC+postWater,postRefHC=c.pvt.postOil+c.pvt.postGas,postRefTotal=postRefHC+c.pvt.postWater;
 const avgP=as.length?sum(as,'p')/as.filter(r=>r.use).length:0,above=avgP>=c.pb;
 const devHC=refHC?(asHC-refHC)/refHC:NaN,devTotal=refTotal?(asTotal-refTotal)/refTotal:NaN,postDevHC=postRefHC?(postHC-postRefHC)/postRefHC:NaN,postDevTotal=postRefTotal?(postTotal-postRefTotal)/postRefTotal:NaN;
 const kOil=asOil?c.pvt.asOil/asOil:NaN,kGas=above?1:(asGas?c.pvt.asGas/asGas:NaN),ratio=c.pvt.asWater===0?Infinity:c.pvt.asOil/c.pvt.asWater,kWater=(c.pvt.asWater===0||ratio>=25)?1:(asWater?c.pvt.asWater/asWater:NaN),kHC=asHC?refHC/asHC:NaN;
 const uAs=Math.hypot(c.uncertainty.asMpfm,c.uncertainty.asRef),uPost=Math.hypot(c.uncertainty.postMpfm,c.uncertainty.postRef),enAs=uAs?Math.abs(devHC*100)/uAs:NaN,enPost=uPost?Math.abs(postDevHC*100)/uPost:NaN;
 const envComplete=Object.values(c.envelope).every(v=>v[0]!=null&&v[1]!=null); const pvtTrace=!!(c.pvt.file&&c.pvt.hash&&c.pvt.version&&c.pvt.approver);
 const rangeOk=envComplete&&as.every(r=>!r.use||([['p','p'],['t','t'],['dp','dp'],['gvf','gvf'],['wlr','wlr']] as const).every(([key,e])=>r[key]>=(c.envelope[e][0] as number)&&r[key]<=(c.envelope[e][1] as number)));
 const gates=[
  ['G01','Contrato da campanha',!!(c.id&&c.asset&&c.tag&&c.serial&&c.reference&&c.responsible&&c.approver)],['G02','MPFM As-Found — registros e duração',as.filter(r=>r.use).length>=c.minRecords&&sum(as,'duration')>=24],['G03','Separador As-Found — referência disponível',refHC>0],['G04','Rastreabilidade PVT As-Found',pvtTrace],['G05','dP histórico real',c.integrity.dp],['G06','Integridade RAW, unidades e timestamps',Object.values(c.integrity).every(Boolean)],['G07','Envelope cadastrado',envComplete],['G08','Operação dentro do envelope',rangeOk],['G09','Laboratório e propriedades',c.pvt.asOil>0&&c.pvt.asGas>0],['G10','Certificados e evidências críticas',c.evidence],['G11','Eventos e exclusões tratados',c.integrity.exclusions],['G12','Regra de K e condição de fase',false],['G13','Aplicação do K comprovada',!!(c.k.date&&c.k.responsible&&c.k.evidence)],['G14','Monitoramento pós-K',post.filter(r=>r.use).length>=c.minRecords&&postRefHC>0&&pvtTrace],['G15','Incerteza e En',Number.isFinite(enAs)&&enAs<=1],['G16','Aprovação formal',c.approvals]
 ] as [string,string,boolean][]; gates[11][2]=gates.slice(0,11).every(g=>g[2]);
 const technical=gates.filter((_,i)=>![12,13,15].includes(i)).every(g=>g[2]); const issue=gates.every(g=>g[2]);
 return {as,post,asOil,asGas,asWater,refOil:c.pvt.asOil,refGas:c.pvt.asGas,refWater:c.pvt.asWater,asHC,asTotal,refHC,refTotal,postHC,postTotal,postRefHC,postRefTotal,devHC,devTotal,postDevHC,postDevTotal,kOil,kGas,kWater,kHC,uAs,uPost,enAs,enPost,avgP,above,gates,technical,issue};
}
const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const pct=(n:number)=>Number.isFinite(n)?`${n<0?'−':''}${fmt(Math.abs(n)*100,2)}%`:'—';
const numOrDash=(n:number|null,d=2)=>n==null?'—':fmt(n,d);
const toNum=(v:unknown):number|null=>{const n=Number(v);return Number.isFinite(n)?n:null};

const nav=[['Visão geral',Home],['Campanha',ClipboardCheck],['Importação',Import],['MPFM',Gauge],['Separador',Droplets],['Laboratório/PVT',Beaker],['Fatores K',SlidersHorizontal],['Pós-K',Activity],['Evidências',FileCheck2],['Relatórios',BarChart3]] as const;
function SparkChart({rows,kind='stability'}:{rows:Row[],kind?:string}){const data=rows.filter(r=>r.use); const W=520,H=188,pad=26; if(!data.length)return <div className="empty">Sem dados para o gráfico.</div>; const vals=kind==='gvf'?data.map(r=>r.gvf):data.map(r=>r.p); const min=Math.min(...vals)*.98,max=Math.max(...vals)*1.02; const points=vals.map((v,i)=>`${pad+i*(W-pad*2)/Math.max(vals.length-1,1)},${H-pad-(v-min)*(H-pad*2)/(max-min||1)}`).join(' ');return <svg viewBox={`0 0 ${W} ${H}`} className="chart"><g className="grid">{[0,1,2,3].map(i=><line key={i} x1={pad} x2={W-pad} y1={pad+i*42} y2={pad+i*42}/>)}</g><polyline points={points} fill="none" stroke="#0b2c5b" strokeWidth="3"/><polyline points={points} fill="none" stroke="#ff1243" strokeWidth="1" strokeDasharray="5 5" transform="translate(0 4)"/></svg>}
function CompareChart({r}:{r:ReturnType<typeof calculate>}){const items=[['Óleo',r.asOil,r.refOil],['Gás',r.asGas,r.refGas],['HC',r.asHC,r.refHC],['Total',r.asTotal,r.refTotal]] as [string,number,number][]; const max=Math.max(...items.flatMap(x=>[x[1],x[2]]));return <div className="bar-chart">{items.map(([n,a,b])=><div className="bar-row" key={n}><span>{n}</span><div><i style={{width:`${a/max*100}%`}}/><em style={{width:`${b/max*100}%`}}/></div><strong>{fmt((a-b)/b*100,1)}%</strong></div>)}<footer><span><b className="dot navy"/>MPFM</span><span><b className="dot magenta"/>Referência</span></footer></div>}

async function parseMpfmWindow(file:File,tag:string,start:string,end:string):Promise<MpfmExtractRow[]>{
 const ab=await file.arrayBuffer();
 const wb=XLSX.read(ab,{cellDates:true});
 const ws=wb.Sheets['BASE_UNICA_MES'];
 if(!ws) return [];
 const startTime=start?new Date(start).getTime():-Infinity;
 const endTime=end?new Date(end).getTime():Infinity;
 const out:MpfmExtractRow[]=[];
 for(const r of XLSX.utils.sheet_to_json<any[]>(ws,{header:1,raw:true})){
  if(r[3]!=='Hourly'||r[13]!==tag) continue;
  const date=r[1],hour=r[2];
  if(!date||!hour) continue;
  const timestamp=`${date}T${hour}:00`;
  const t=new Date(timestamp).getTime();
  if(Number.isNaN(t)||t<startTime||t>endTime) continue;
  out.push({timestamp,use:true,duration:1,quality:'',p:toNum(r[45]),t:toNum(r[46]),dp:null,gvf:null,wlr:null,oil:toNum(r[16]),gas:toNum(r[15]),water:toNum(r[18]),oilCorr:toNum(r[21]),gasCorr:toNum(r[20]),waterCorr:toNum(r[23])});
 }
 return out;
}
async function parseSeparatorWindow(file:File,start:string,end:string):Promise<SeparatorExtractRow[]>{
 const ab=await file.arrayBuffer();
 const wb=XLSX.read(ab,{cellDates:true});
 const startTime=start?new Date(start).getTime():-Infinity;
 const endTime=end?new Date(end).getTime():Infinity;
 const readings:Record<string,{p:number|null,t:number|null,oilGv:number|null,oilRho:number|null,oilMass:number|null,gasMass:number|null,gasStd:number|null,waterMass:number|null,waterVol:number|null}>={};
 const ensure=(timestamp:string)=>readings[timestamp]??(readings[timestamp]={p:null,t:null,oilGv:null,oilRho:null,oilMass:null,gasMass:null,gasStd:null,waterMass:null,waterVol:null});
 const eachRow=(sheetName:string,fn:(r:any[],timestamp:string)=>void)=>{
  const ws=wb.Sheets[sheetName];
  if(!ws) return;
  let currentDay='';
  for(const r of XLSX.utils.sheet_to_json<any[]>(ws,{header:1,raw:true})){
   const marker=String(r[2]??'');
   const dayMatch=/Data:\s*(\d{4}-\d{2}-\d{2})/.exec(marker);
   if(dayMatch){currentDay=dayMatch[1];continue}
   if(!currentDay||marker==='DAY') continue;
   const hourNum=Number(marker);
   if(!Number.isInteger(hourNum)||hourNum<1||hourNum>24) continue;
   const timestamp=`${currentDay}T${String(hourNum-1).padStart(2,'0')}:00`;
   const t=new Date(timestamp).getTime();
   if(Number.isNaN(t)||t<startTime||t>endTime) continue;
   fn(r,timestamp);
  }
 };
 eachRow('separador oleo',(r,timestamp)=>{const e=ensure(timestamp);e.p=toNum(r[4]);e.t=toNum(r[5]);e.oilGv=toNum(r[9]);e.oilRho=toNum(r[17]);e.oilMass=toNum(r[11])});
 eachRow('separador gas',(r,timestamp)=>{const e=ensure(timestamp);e.gasMass=toNum(r[9]);const std=toNum(r[8]);e.gasStd=std!=null?std/1000:null});
 eachRow('separador agua',(r,timestamp)=>{const e=ensure(timestamp);e.waterMass=toNum(r[10]);e.waterVol=toNum(r[8])});
 return Object.entries(readings).map(([timestamp,v])=>({timestamp,use:true,durationH:1,quality:'',pressureBarg:v.p,temperatureC:v.t,oilGvLineM3:v.oilGv,oilRhoCoriolisKgm3:v.oilRho,oilMassDirectT:v.oilMass,gasMassT:v.gasMass,waterMassT:v.waterMass,gasStdKsm3:v.gasStd,waterVolM3:v.waterVol,sourceRef:file.name}));
}
function App(){
 const [c,setC]=useState<Campaign>(()=>{try{return JSON.parse(localStorage.getItem('mpfm-campaign')||'null')||initial}catch{return initial}}),[active,setActive]=useState('Visão geral'),[drawer,setDrawer]=useState(false),[toast,setToast]=useState(''),[mobile,setMobile]=useState(false),[novaCampanha,setNovaCampanha]=useState(false); const fileRef=useRef<HTMLInputElement>(null); const r=useMemo(()=>calculate(c),[c]);
 useEffect(()=>{let alive=true;fetch(`/api/calibration?campaignId=${encodeURIComponent(c.id)}`).then(res=>res.json()).then(data=>{if(alive&&data.status==='ok'&&data.campaign)setC(data.campaign)}).catch(()=>{});return ()=>{alive=false}},[]);
 const update=(key:keyof Campaign,value:any)=>setC(x=>({...x,[key]:value})); const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(''),2600)};
 const updateSection=(section:'pvt'|'uncertainty'|'k',key:string,value:any)=>setC(x=>({...x,[section]:{...x[section],[key]:value}}));
 const updateEnvelope=(axis:'p'|'t'|'dp'|'gvf'|'wlr',index:0|1,value:number|null)=>setC(x=>{const arr:[number|null,number|null]=[...x.envelope[axis]] as any;arr[index]=value;return {...x,envelope:{...x.envelope,[axis]:arr}}});
 const save=async()=>{
  localStorage.setItem('mpfm-campaign',JSON.stringify(c));
  try{
   const res=await fetch(`/api/calibration?campaignId=${encodeURIComponent(c.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:c.id,revision:c.revision,nature:c.nature,asset:c.asset,well:c.well,tag:c.tag,serial:c.serial,reference:c.reference,start:c.start,end:c.end,postStart:c.postStart,postEnd:c.postEnd,pb:c.pb,hcLimit:c.hcLimit,totalLimit:c.totalLimit,pvtLimit:c.pvtLimit,kMin:c.kMin,kMax:c.kMax,minRecords:c.minRecords,pvtMonths:c.pvtMonths,timezone:c.timezone,responsible:c.responsible,approver:c.approver,envelope:c.envelope,pvt:c.pvt,uncertainty:c.uncertainty,k:c.k,evidence:c.evidence,approvals:c.approvals})});
   if(!res.ok) throw new Error(String(res.status));
   flash('Campanha salva no navegador e na base real.');
  }catch{
   flash('Campanha salva neste navegador (base real indisponível).');
  }
 };
 const importFile=async(f:File)=>{const ab=await f.arrayBuffer();const wb=XLSX.read(ab,{cellDates:true});const v=(s:string,a:string)=>wb.Sheets[s]?.[a]?.v; const nc={...c,id:v('01_CAMPANHA','B5')||c.id,revision:v('01_CAMPANHA','B6')||c.revision,asset:v('01_CAMPANHA','B8')||c.asset,well:v('01_CAMPANHA','B9')||c.well,tag:v('01_CAMPANHA','B10')||c.tag,serial:v('01_CAMPANHA','B11')||c.serial,reference:v('01_CAMPANHA','B13')||c.reference,pb:Number(v('01_CAMPANHA','B20'))||c.pb}; const ws=wb.Sheets['IN_01_MPFM']; if(ws){const a=XLSX.utils.sheet_to_json<any[]>(ws,{header:1,raw:true});const rows=a.slice(5).filter(x=>x[1]&&x[2]).map(x=>({condition:x[1],timestamp:x[2] instanceof Date?x[2].toISOString():String(x[2]),use:x[3]!=='NÃO',duration:Number(x[4])||0,p:Number(x[6])||0,t:Number(x[7])||0,dp:Number(x[8])||0,gvf:Number(x[9])||0,wlr:Number(x[10])||0,oil:Number(x[11])||0,gas:Number(x[12])||0,water:Number(x[13])||0,oilCorr:Number(x[14])||0,gasCorr:Number(x[15])||0,waterCorr:Number(x[16])||0}));if(rows.length)nc.rows=rows}setC(nc);flash(`Excel importado: ${f.name}`)};
 const exportExcel=()=>{const wb=XLSX.utils.book_new(); const camp=[['Campo','Valor','Unidade'],['Campaign ID',c.id],['Revisão',c.revision],['Natureza',c.nature],['Ativo',c.asset],['Poço/Riser',c.well],['TAG MPFM',c.tag],['Número de série',c.serial],['Referência',c.reference],['Pb',c.pb,'barg'],['Limite HC',c.hcLimit,'%'],['Limite total',c.totalLimit,'%'],['Timezone',c.timezone],['Responsável',c.responsible],['Aprovador',c.approver]]; XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(camp),'01_CAMPANHA'); const rows=[['Campaign ID','Condição','Timestamp','Usar?','Duração (h)','P (barg)','T (°C)','dP (kPa)','GVF (%)','WLR (%)','Óleo uncorr (t)','Gás uncorr (t)','Água uncorr (t)','Óleo corr (t)','Gás corr (t)','Água corr (t)'],...c.rows.map(x=>[c.id,x.condition,x.timestamp,x.use?'SIM':'NÃO',x.duration,x.p,x.t,x.dp,x.gvf,x.wlr,x.oil,x.gas,x.water,x.oilCorr,x.gasCorr,x.waterCorr])];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'IN_01_MPFM'); const out=[['Bloco','Indicador','Valor','Unidade'],['As-Found','Massa HC MPFM',r.asHC,'t'],['As-Found','Massa HC referência',r.refHC,'t'],['As-Found','Desvio HC',r.devHC,'%'],['K','K óleo',r.kOil],['K','K gás',r.kGas],['K','K água',r.kWater],['Pós-K','Desvio HC',r.postDevHC,'%'],['Incerteza','En As-Found',r.enAs],['Incerteza','En Pós-K',r.enPost],['Decisão','Validade técnica',r.technical?'VÁLIDO':'NÃO VÁLIDO'],['Decisão','Prontidão',r.issue?'APTO PARA EMISSÃO':'NÃO EMITIR — BLOQUEIO']];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(out),'06_EXPORTACAO'); XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Gate','Verificação','Status'],...r.gates.map(g=>[g[0],g[1],g[2]?'OK':'PENDENTE'])]),'03_VALIDACAO');XLSX.writeFile(wb,`${c.id}_${c.revision.replace(/\s/g,'')}_${c.tag}.xlsx`);flash('Excel preenchido gerado.')};
 return <div className="app"><aside className={mobile?'open':''}><div className="brand"><span>∿</span><div><b>METROLOG</b><small>MEDIÇÃO CONFIÁVEL</small></div></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'active':''} onClick={()=>{setActive(n);setMobile(false)}}><I size={19}/><span>{n}</span></button>)}</nav><div className="version">Motor MPFM v2.1<br/>Campanha local</div><a className="back-link" href="/"><Home size={15}/>Voltar ao Portal SGM</a></aside>{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<main><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div className="selector"><small>Campanha ativa</small><b>{c.id} | {c.asset} | P4</b></div><button className="icon" title="Solicitar nova calibração" onClick={()=>setNovaCampanha(true)}><Plus size={17}/></button><span className="sync"><CheckCircle2 size={17}/> Sincronizado localmente</span><div className="header-actions"><input ref={fileRef} type="file" accept=".xlsx,.xls" hidden onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/><button onClick={()=>fileRef.current?.click()}><Upload size={17}/>Importar</button><button className="primary" onClick={exportExcel}><FileSpreadsheet size={17}/>Exportar Excel</button><button className="icon" onClick={()=>setDrawer(true)}><Settings2/></button></div></header>{active==='Visão geral'?<Overview c={c} r={r} setDrawer={setDrawer}/>:active==='Campanha'?<CampanhaTab c={c} update={update} updateEnvelope={updateEnvelope} save={save}/>:active==='Fatores K'?<FatoresKTab c={c} updateSection={updateSection} r={r} save={save}/>:active==='Pós-K'?<PosKTab c={c} updateSection={updateSection} r={r} save={save}/>:active==='Laboratório/PVT'?<LaboratorioPvtTab c={c} updateSection={updateSection} save={save}/>:active==='MPFM'?<MPFMTab c={c}/>:active==='Separador'?<SeparadorTab c={c}/>:active==='Evidências'?<EvidenciasTab c={c} r={r}/>:active==='Importação'?<ImportacaoTab fileRef={fileRef}/>:active==='Relatórios'?<RelatoriosTab exportExcel={exportExcel}/>:<EmConstrucao tab={active}/>}</main>{drawer&&<Drawer c={c} update={update} close={()=>setDrawer(false)} save={()=>{save();setDrawer(false)}}/>}{novaCampanha&&<NovaCampanhaModal close={()=>setNovaCampanha(false)} onCreated={created=>{setC(created);localStorage.setItem('mpfm-campaign',JSON.stringify(created));setNovaCampanha(false);setActive('Campanha');flash('Campanha criada. Continue o preenchimento na aba Campanha.')}}/>}{toast&&<div className="toast"><CheckCircle2/>{toast}</div>}</div>}
function Kpi({label,value,limit,ok}:{label:string,value:string,limit:string,ok:boolean}){return <div className="kpi"><small>{label}</small><strong className={ok?'positive':'negative'}>{value}</strong><span>{limit}</span>{ok?<CheckCircle2/>:<AlertTriangle/>}</div>}
function Panel({title,subtitle,children,className=''}:{title:string,subtitle:string,children:React.ReactNode,className?:string}){return <article className={`panel ${className}`}><header><div><h2>{title}</h2><p>{subtitle}</p></div><button><ChevronRight/></button></header>{children}</article>}
function EmConstrucao({tab}:{tab:string}){return <div className="empty"><div><b>{tab}</b><br/>Tela ainda não implementada.</div></div>}
function Overview({c,r,setDrawer}:{c:Campaign,r:ReturnType<typeof calculate>,setDrawer:(v:boolean)=>void}){return <div className="page"><div className="title-row"><div><h1>MPFM Performance & Calibration — Riser P4</h1><p>Campanha controlada, decisão metrológica e rastreabilidade end-to-end.</p></div><button className="primary" onClick={()=>setDrawer(true)}>Editar campanha</button></div><div className="steps">{['Dados e importação','Verificações iniciais','Performance As-Found','Pós-K e validação','Aprovação técnica','Emissão'].map((s,i)=><div className={i<3?'done':i===3?'current':''} key={s}><span>{i<3?<Check size={15}/>:i+1}</span><b>{s}</b></div>)}</div><div className="status-band"><div className={Math.abs(r.postDevHC)<=c.hcLimit?'ok':'bad'}><CheckCircle2/><span>Resultado técnico pós-K:<b>{Math.abs(r.postDevHC)<=c.hcLimit?'ATENDE':'NÃO ATENDE'}</b><small>Comparação independente na P/T do MPFM.</small></span></div><div className={r.issue?'ok':'bad'}><ShieldAlert/><span>Prontidão de emissão:<b>{r.issue?'APTA':'BLOQUEADA'}</b><small>{r.gates.filter(g=>!g[2]).length} pendências impedem o fechamento.</small></span></div></div><div className="kpis"><Kpi label="Desvio HC As-Found" value={pct(r.devHC)} limit={`Critério: ≤ ${fmt(c.hcLimit*100,0)}%`} ok={Math.abs(r.devHC)<=c.hcLimit}/><Kpi label="Desvio HC Pós-K" value={pct(r.postDevHC)} limit={`Critério: ≤ ${fmt(c.hcLimit*100,0)}%`} ok={Math.abs(r.postDevHC)<=c.hcLimit}/><Kpi label="En Pós-K" value={fmt(r.enPost,3)} limit="Critério: ≤ 1,000" ok={r.enPost<=1}/><Kpi label="K óleo calculado" value={fmt(r.kOil,5)} limit="Base mássica equalizada" ok={r.kOil>=c.kMin&&r.kOil<=c.kMax}/></div><div className="dashboard-grid"><Panel title="MPFM × referência equalizada — As-Found" subtitle="Comparação em massa (t)"><CompareChart r={r}/></Panel><Panel title="Estabilidade operacional — As-Found" subtitle="Pressão horária (barg)"><SparkChart rows={r.as}/></Panel><Panel title="Matriz dos 16 gates" subtitle="O pior gate obrigatório prevalece" className="gates"><div className="gate-grid">{r.gates.map(g=><button key={g[0]} className={g[2]?'pass':'pending'} title={g[1]}><span>{g[0]}</span>{g[2]?<CheckCircle2/>:<AlertTriangle/>}<small>{g[1]}</small></button>)}</div><div className="legend"><span><i className="green"/>Atende</span><span><i className="amber"/>Pendente</span></div></Panel><Panel title="Pendências prioritárias" subtitle="Ações necessárias para emissão"><div className="issues">{r.gates.filter(g=>!g[2]).slice(0,6).map((g,i)=><div key={g[0]}><b>{i<2?'Alta':'Média'}</b><span><strong>{g[0]} — {g[1]}</strong><small>{g[0]==='G04'?'Anexar arquivo PVT, hash, versão e aprovação.':g[0]==='G07'?'Cadastrar envelope numérico aprovado.':'Completar dados e evidências da etapa.'}</small></span><em>Aberta</em></div>)}</div></Panel></div></div>}
function CampanhaTab({c,update,updateEnvelope,save}:{c:Campaign,update:(k:keyof Campaign,v:any)=>void,updateEnvelope:(axis:'p'|'t'|'dp'|'gvf'|'wlr',index:0|1,value:number|null)=>void,save:()=>void}){
 const field=(label:string,key:keyof Campaign,type='text',unit='')=><label><span>{label}</span><div><input type={type} value={String(c[key]??'')} onChange={e=>update(key,type==='number'?Number(e.target.value):e.target.value)}/>{unit&&<em>{unit}</em>}</div></label>;
 const envField=(label:string,axis:'p'|'t'|'dp'|'gvf'|'wlr',unit:string)=><label><span>{label}</span><div className="envelope-pair"><input type="number" placeholder="mín" value={c.envelope[axis][0]??''} onChange={e=>updateEnvelope(axis,0,e.target.value===''?null:Number(e.target.value))}/><input type="number" placeholder="máx" value={c.envelope[axis][1]??''} onChange={e=>updateEnvelope(axis,1,e.target.value===''?null:Number(e.target.value))}/><em>{unit}</em></div></label>;
 return <div className="page"><div className="title-row"><div><h1>Campanha</h1><p>Dados gerais, critérios e envelope operacional.</p></div></div><div className="form">{field('Campaign ID','id')}{field('Ativo / instalação','asset')}{field('Poço / Riser','well')}{field('TAG do MPFM','tag')}{field('Número de série','serial')}{field('Referência autorizada','reference')}{field('Pressão de bolha','pb','number','barg')}{field('Limite de desvio HC','hcLimit','number','fração')}{field('Limite de desvio total','totalLimit','number','fração')}{field('Timezone','timezone')}{field('Responsável técnico','responsible')}{field('Aprovador','approver')}{field('Início da janela As-Found','start','datetime-local')}{field('Fim da janela As-Found','end','datetime-local')}{field('Início da janela Pós-K','postStart','datetime-local')}{field('Fim da janela Pós-K','postEnd','datetime-local')}{envField('Envelope de pressão','p','barg')}{envField('Envelope de temperatura','t','°C')}{envField('Envelope de dP','dp','kPa')}{envField('Envelope de GVF','gvf','%')}{envField('Envelope de WLR','wlr','%')}<label><span>Evidências completas</span><input type="checkbox" checked={c.evidence} onChange={e=>update('evidence',e.target.checked)}/></label><label><span>Aprovações formalizadas</span><input type="checkbox" checked={c.approvals} onChange={e=>update('approvals',e.target.checked)}/></label></div><button className="primary" onClick={save}><Save size={16}/>Salvar</button></div>
}
function FatoresKTab({c,updateSection,r,save}:{c:Campaign,updateSection:(section:'pvt'|'uncertainty'|'k',key:string,value:any)=>void,r:ReturnType<typeof calculate>,save:()=>void}){
 const num=(label:string,key:keyof Campaign['k'])=><label><span>{label}</span><div><input type="number" value={String(c.k[key]??'')} onChange={e=>updateSection('k',key,e.target.value===''?null:Number(e.target.value))}/></div></label>;
 const txt=(label:string,key:keyof Campaign['k'])=><label><span>{label}</span><div><input type="text" value={String(c.k[key]??'')} onChange={e=>updateSection('k',key,e.target.value)}/></div></label>;
 return <div className="page"><div className="title-row"><div><h1>Fatores K</h1><p>K aprovado e aplicado por fase, comparado ao K calculado.</p></div></div><div className="kpis"><Kpi label="K óleo calculado" value={fmt(r.kOil,5)} limit="Base mássica equalizada" ok={r.kOil>=c.kMin&&r.kOil<=c.kMax}/><Kpi label="K gás calculado" value={fmt(r.kGas,5)} limit="Base mássica equalizada" ok={r.kGas>=c.kMin&&r.kGas<=c.kMax}/><Kpi label="K água calculado" value={fmt(r.kWater,5)} limit="Base mássica equalizada" ok={r.kWater>=c.kMin&&r.kWater<=c.kMax}/></div><div className="form">{num('K óleo aprovado','oilApproved')}{num('K óleo aplicado','oilApplied')}{num('K gás aprovado','gasApproved')}{num('K gás aplicado','gasApplied')}{num('K água aprovado','waterApproved')}{num('K água aplicado','waterApplied')}{txt('Data de aplicação','date')}{txt('Responsável','responsible')}{txt('Evidência','evidence')}</div><button className="primary" onClick={save}><Save size={16}/>Salvar</button></div>
}
function PosKTab({c,updateSection,r,save}:{c:Campaign,updateSection:(section:'pvt'|'uncertainty'|'k',key:string,value:any)=>void,r:ReturnType<typeof calculate>,save:()=>void}){
 const num=(label:string,key:keyof Campaign['uncertainty'])=><label><span>{label}</span><div><input type="number" value={String(c.uncertainty[key]??'')} onChange={e=>updateSection('uncertainty',key,e.target.value===''?null:Number(e.target.value))}/></div></label>;
 return <div className="page"><div className="title-row"><div><h1>Pós-K</h1><p>Incerteza pós-K e resultado da validação.</p></div></div><div className="status-band"><div className={Math.abs(r.postDevHC)<=c.hcLimit?'ok':'bad'}><CheckCircle2/><span>Resultado técnico pós-K:<b>{Math.abs(r.postDevHC)<=c.hcLimit?'ATENDE':'NÃO ATENDE'}</b><small>Desvio HC: {pct(r.postDevHC)}</small></span></div></div><div className="kpis"><Kpi label="Desvio HC Pós-K" value={pct(r.postDevHC)} limit={`Critério: ≤ ${fmt(c.hcLimit*100,0)}%`} ok={Math.abs(r.postDevHC)<=c.hcLimit}/><Kpi label="Desvio Total Pós-K" value={pct(r.postDevTotal)} limit={`Critério: ≤ ${fmt(c.totalLimit*100,0)}%`} ok={Math.abs(r.postDevTotal)<=c.totalLimit}/><Kpi label="En Pós-K" value={fmt(r.enPost,3)} limit="Critério: ≤ 1,000" ok={r.enPost<=1}/></div><div className="form">{num('Incerteza MPFM pós-K','postMpfm')}{num('Incerteza referência pós-K','postRef')}</div><button className="primary" onClick={save}><Save size={16}/>Salvar</button></div>
}
function LaboratorioPvtTab({c,updateSection,save}:{c:Campaign,updateSection:(section:'pvt'|'uncertainty'|'k',key:string,value:any)=>void,save:()=>void}){
 const num=(label:string,key:keyof Campaign['pvt'])=><label><span>{label}</span><div><input type="number" value={String(c.pvt[key]??'')} onChange={e=>updateSection('pvt',key,e.target.value===''?null:Number(e.target.value))}/></div></label>;
 const txt=(label:string,key:keyof Campaign['pvt'])=><label><span>{label}</span><div><input type="text" value={String(c.pvt[key]??'')} onChange={e=>updateSection('pvt',key,e.target.value)}/></div></label>;
 const lab=c.raw?.labResults??[];
 return <div className="page"><div className="title-row"><div><h1>Laboratório/PVT</h1><p>Rastreabilidade PVT e massas de referência por condição.</p></div></div><div className="form">{txt('Arquivo PVT','file')}{txt('Hash (SHA-256)','hash')}{txt('Software','software')}{txt('Versão','version')}{txt('Aprovador','approver')}{num('Óleo As-Found','asOil')}{num('Gás As-Found','asGas')}{num('Água As-Found','asWater')}{num('Óleo Pós-K','postOil')}{num('Gás Pós-K','postGas')}{num('Água Pós-K','postWater')}</div><button className="primary" onClick={save}><Save size={16}/>Salvar</button><Panel title="Resultados de laboratório" subtitle={`${lab.length} amostras — só leitura`}>{lab.length?<div className="table-wrap"><table><thead><tr><th>Amostra</th><th>Usar?</th><th>Coletado em</th><th>Tipo</th><th>BSW (%)</th><th>ρ óleo padrão (kg/m³)</th><th>ρ gás padrão (kg/sm³)</th><th>ρ água padrão (kg/m³)</th><th>Fe</th><th>Rs</th><th>Método</th><th>Relatório</th><th>Status</th></tr></thead><tbody>{lab.map((row,i)=><tr key={i}><td>{row.sample_id||'—'}</td><td>{row.use_flag?'Sim':'Não'}</td><td>{row.sampled_at||'—'}</td><td>{row.sample_type||'—'}</td><td>{numOrDash(row.bsw_pct,2)}</td><td>{numOrDash(row.rho_oil_std_kgm3,2)}</td><td>{numOrDash(row.rho_gas_std_kgsm3,4)}</td><td>{numOrDash(row.rho_water_std_kgm3,2)}</td><td>{numOrDash(row.fe,4)}</td><td>{numOrDash(row.rs,2)}</td><td>{row.method||'—'}</td><td>{row.report_id||'—'}</td><td>{row.status||'—'}</td></tr>)}</tbody></table></div>:<div className="empty">Nenhum resultado de laboratório carregado ainda.</div>}</Panel></div>
}
function MPFMTab({c}:{c:Campaign}){
 return <div className="page"><div className="title-row"><div><h1>MPFM</h1><p>Leituras importadas do MPFM, condição As-Found e Pós-K.</p></div></div><Panel title="Leituras MPFM" subtitle={`${c.rows.length} registros`}>{c.rows.length?<div className="table-wrap"><table><thead><tr><th>Condição</th><th>Timestamp</th><th>Usar?</th><th>Duração (h)</th><th>P (barg)</th><th>T (°C)</th><th>dP (kPa)</th><th>GVF (%)</th><th>WLR (%)</th><th>Óleo (t)</th><th>Gás (t)</th><th>Água (t)</th><th>Óleo corr (t)</th><th>Gás corr (t)</th><th>Água corr (t)</th></tr></thead><tbody>{c.rows.map((row,i)=><tr key={i}><td>{row.condition}</td><td>{row.timestamp}</td><td>{row.use?'Sim':'Não'}</td><td>{fmt(row.duration,1)}</td><td>{fmt(row.p,2)}</td><td>{fmt(row.t,2)}</td><td>{fmt(row.dp,2)}</td><td>{fmt(row.gvf,2)}</td><td>{fmt(row.wlr,2)}</td><td>{fmt(row.oil,3)}</td><td>{fmt(row.gas,3)}</td><td>{fmt(row.water,3)}</td><td>{row.oilCorr!=null?fmt(row.oilCorr,3):'—'}</td><td>{row.gasCorr!=null?fmt(row.gasCorr,3):'—'}</td><td>{row.waterCorr!=null?fmt(row.waterCorr,3):'—'}</td></tr>)}</tbody></table></div>:<div className="empty">Nenhuma leitura importada ainda.</div>}</Panel></div>
}
function SeparadorTab({c}:{c:Campaign}){
 const rows=c.raw?.separatorRows??[];
 return <div className="page"><div className="title-row"><div><h1>Separador</h1><p>Leituras do separador de teste, condição As-Found e Pós-K.</p></div></div><Panel title="Leituras do separador" subtitle={`${rows.length} registros`}>{rows.length?<div className="table-wrap"><table><thead><tr><th>Condição</th><th>Timestamp</th><th>Usar?</th><th>Duração (h)</th><th>Qualidade</th><th>P (barg)</th><th>T (°C)</th><th>Óleo GV linha (m³)</th><th>Óleo ρ Coriolis (kg/m³)</th><th>Óleo massa direta (t)</th><th>Gás (t)</th><th>Água (t)</th><th>Gás padrão (ksm³)</th><th>Água (m³)</th><th>Referência</th></tr></thead><tbody>{rows.map((row,i)=><tr key={i}><td>{row.condition}</td><td>{row.timestamp}</td><td>{row.use_flag?'Sim':'Não'}</td><td>{numOrDash(row.duration_h,1)}</td><td>{row.quality||'—'}</td><td>{numOrDash(row.pressure_barg,2)}</td><td>{numOrDash(row.temperature_c,2)}</td><td>{numOrDash(row.oil_gv_line_m3,3)}</td><td>{numOrDash(row.oil_rho_coriolis_kgm3,2)}</td><td>{numOrDash(row.oil_mass_direct_t,3)}</td><td>{numOrDash(row.gas_mass_t,3)}</td><td>{numOrDash(row.water_mass_t,3)}</td><td>{numOrDash(row.gas_std_ksm3,3)}</td><td>{numOrDash(row.water_vol_m3,3)}</td><td>{row.source_ref||'—'}</td></tr>)}</tbody></table></div>:<div className="empty">Nenhuma leitura de separador carregada ainda.</div>}</Panel></div>
}
function EvidenciasTab({c,r}:{c:Campaign,r:ReturnType<typeof calculate>}){
 const g10=r.gates.find(g=>g[0]==='G10');
 return <div className="page"><div className="title-row"><div><h1>Evidências</h1><p>Checklist de evidências e aprovações.</p></div></div><div className="status-band"><div className={c.evidence?'ok':'bad'}><CheckCircle2/><span>Evidências completas:<b>{c.evidence?'SIM':'NÃO'}</b><small>Editável na aba Campanha.</small></span></div><div className={c.approvals?'ok':'bad'}><ShieldAlert/><span>Aprovações formalizadas:<b>{c.approvals?'SIM':'NÃO'}</b><small>Editável na aba Campanha.</small></span></div></div><div className="kpis"><Kpi label="Gate G10 — Certificados e evidências críticas" value={g10&&g10[2]?'Atende':'Pendente'} limit="Ver matriz de gates completa em Visão geral" ok={!!(g10&&g10[2])}/></div><div className="form"><div className="validation"><CheckCircle2/><span><b>Evidência de aplicação do K</b><small>{c.k.evidence||'Nenhuma evidência registrada.'} — editável na aba Fatores K.</small></span></div></div></div>
}
function ImportacaoTab({fileRef}:{fileRef:React.RefObject<HTMLInputElement>}){
 return <div className="page"><div className="title-row"><div><h1>Importação</h1><p>Carrega uma nova campanha a partir do Excel de calibração.</p></div></div><div className="form"><div className="validation"><CheckCircle2/><span><b>Formato aceito</b><small>Excel (.xlsx/.xls) com as abas "01_CAMPANHA" e "IN_01_MPFM" — mesmo modelo do botão "Importar" no topo da tela.</small></span></div><button className="primary" onClick={()=>fileRef.current?.click()}><Upload size={16}/>Selecionar arquivo</button></div></div>
}
function RelatoriosTab({exportExcel}:{exportExcel:()=>void}){
 return <div className="page"><div className="title-row"><div><h1>Relatórios</h1><p>Exporta a campanha completa em Excel.</p></div></div><div className="form"><div className="validation"><CheckCircle2/><span><b>Conteúdo do arquivo gerado</b><small>Abas "01_CAMPANHA", "IN_01_MPFM", "03_VALIDACAO" (matriz de gates) e "06_EXPORTACAO" (resultado técnico).</small></span></div><button className="primary" onClick={exportExcel}><FileSpreadsheet size={16}/>Exportar Excel</button></div></div>
}
function Drawer({c,update,close,save}:{c:Campaign,update:(k:keyof Campaign,v:any)=>void,close:()=>void,save:()=>void}){const field=(label:string,key:keyof Campaign,type='text',unit='')=><label><span>{label}<i>*</i></span><div><input type={type} value={String(c[key]??'')} onChange={e=>update(key,type==='number'?Number(e.target.value):e.target.value)}/>{unit&&<em>{unit}</em>}</div></label>;return <><div className="drawer-scrim" onClick={close}/><aside className="drawer"><header><div><h2>Detalhes da campanha</h2><p>Informações gerais e critérios</p></div><button onClick={close}><X/></button></header><div className="form">{field('Campaign ID','id')}{field('Ativo / instalação','asset')}{field('Poço / Riser','well')}{field('TAG do MPFM','tag')}{field('Número de série','serial')}{field('Referência autorizada','reference')}{field('Pressão de bolha','pb','number','barg')}{field('Limite de desvio HC','hcLimit','number','fração')}{field('Limite de desvio total','totalLimit','number','fração')}{field('Timezone','timezone')}{field('Responsável técnico','responsible')}{field('Aprovador','approver')}<div className="validation"><CheckCircle2/><span><b>Validação imediata</b><small>Campos vazios são refletidos automaticamente nos gates.</small></span></div></div><footer><button onClick={close}>Cancelar</button><button className="primary" onClick={save}><Save/>Salvar</button></footer></aside></>}
function blankCampaign(id:string):Campaign{
 return {id,revision:'',nature:'',asset:'',well:'',tag:'',serial:'',type:'',reference:'',start:'',end:'',postStart:'',postEnd:'',pb:0,hcLimit:0,totalLimit:0,pvtLimit:0,kMin:0,kMax:0,minRecords:0,pvtMonths:0,timezone:'',responsible:'',approver:'',envelope:{p:[null,null],t:[null,null],dp:[null,null],gvf:[null,null],wlr:[null,null]},pvt:{asOil:0,asGas:0,asWater:0,postOil:0,postGas:0,postWater:0,file:'',hash:'',software:'',version:'',approver:''},uncertainty:{asMpfm:0,asRef:0,postMpfm:0,postRef:0},k:{oilApproved:0,gasApproved:0,waterApproved:0,oilApplied:0,gasApplied:0,waterApplied:0,date:'',responsible:'',evidence:''},integrity:{raw:false,dp:false,units:false,timezone:false,gaps:false,exclusions:false},evidence:false,approvals:false,rows:[]}
}
function NovaCampanhaModal({close,onCreated}:{close:()=>void,onCreated:(c:Campaign)=>void}){
 const [form,setForm]=useState({id:'',asset:'',well:'',tag:'',serial:'',reference:'',revision:'Rev. 0',nature:'COMISSIONAMENTO',responsible:'',approver:''});
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 const set=(key:keyof typeof form,value:string)=>setForm(x=>({...x,[key]:value}));
 const field=(label:string,key:keyof typeof form)=><label><span>{label}<i>*</i></span><div><input type="text" value={form[key]} onChange={e=>set(key,e.target.value)}/></div></label>;
 const submit=async()=>{
  if(!form.id||!form.tag){setError('Campaign ID e TAG são obrigatórios.');return}
  setBusy(true);setError('');
  const body={...blankCampaign(form.id),asset:form.asset,well:form.well,tag:form.tag,serial:form.serial,reference:form.reference,revision:form.revision,nature:form.nature,responsible:form.responsible,approver:form.approver};
  try{
   const res=await fetch('/api/calibration',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
   const data=await res.json();
   if(!res.ok||data.status!=='ok'){setError(data.error||'Falha ao criar campanha.');setBusy(false);return}
   onCreated(data.campaign);
  }catch{setError('Base real indisponível — não foi possível criar a campanha.');setBusy(false)}
 };
 return <><div className="drawer-scrim" onClick={close}/><aside className="drawer"><header><div><h2>Solicitar calibração</h2><p>Dados básicos da nova campanha</p></div><button onClick={close}><X/></button></header><div className="form">{field('Campaign ID','id')}{field('Ativo / instalação','asset')}{field('Poço / Riser','well')}{field('TAG do MPFM','tag')}{field('Número de série','serial')}{field('Referência autorizada','reference')}{field('Revisão','revision')}{field('Natureza','nature')}{field('Responsável técnico','responsible')}{field('Aprovador','approver')}{error&&<p className="form-error">{error}</p>}</div><footer><button onClick={close}>Cancelar</button><button className="primary" onClick={submit} disabled={busy}><Save/>{busy?'Criando…':'Criar campanha'}</button></footer></aside></>
}
if(typeof document!=='undefined') createRoot(document.getElementById('root')!).render(<App/>);
